name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed
      - converted_to_draft

jobs:
  ProjectAutomations:
    uses: Oztechan/Global/.github/workflows/reusable-project-submodules.yml@d8c3bac8260f401449f8eb3abcc20c1dec90b65e
    with:
      project_id: 1
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
